# -----------------------------------------------
# "test" PROFILE (For 'mvn clean test')
# This file is ONLY active when running automated tests.
# -----------------------------------------------
# 1. Import Secrets
spring.config.import=optional:dotenv:.env
# 2. Database (DataSource) Configuration
# --- CRITICAL: We use a DIFFERENT database for testing ---
spring.datasource.url=jdbc:postgresql://localhost:5432/kinesis_test_db
spring.datasource.username=postgres
spring.datasource.password=Ramayan786@
# 3. JPA & Hibernate Configuration
# --- CRITICAL: 'create-drop' ---
# This wipes and recreates the DB for every test run.
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
# 4. JWT (JSON WEB TOKEN) SECURITY
app.jwt.secret=ghgdgdgfshdgfftrgfxfc21324t56rry(*&^%jhfhgf
# 1 hour for tests
app.jwt.expiration-ms=3600000
# 5. Security Hardening
# Use 10 for tests, it's faster than 11
security.bcrypt.strength=10
# 6. Logging Configuration
# Keep test logs quieter
logging.level.com.myapp.kinesis=INFO