# -----------------------------------------------
# KINESIS - MASTER CONFIGURATION
# -----------------------------------------------
# This file contains settings SHARED by ALL environments (dev, test, prod).
# 1. Set the application name
spring.application.name=kinesis
# 2. Set the DEFAULT active profile
# When you just click "Run" in your IDE, this tells Spring
# to load the "application-dev.properties" file automatically.
spring.profiles.active=dev
# 3. Enable Java 21 Virtual Threads for all environments
spring.threads.virtual.enabled=true